# Copyright (c) 2026 The ZMK Next Contributors
# SPDX-License-Identifier: MIT

description: Runtime Config Resource Limit Test Behavior

compatible: "zmk,behavior-runtime-config-resource-limit-test"

include: zero_param.yaml
