# Copyright (c) 2026 The ZMK Next Contributors
# SPDX-License-Identifier: MIT

description: Runtime Config Mod-Morph Test Behavior

compatible: "zmk,behavior-runtime-config-mod-morph-test"

include: zero_param.yaml
