# Copyright (c) 2026 The ZMK Next Contributors
# SPDX-License-Identifier: MIT

description: Runtime Config Idle-Activation Seed Test Behavior

compatible: "zmk,behavior-runtime-config-idle-seed-test"

include: zero_param.yaml
